# Site settings
port: 4000
title: Math Demo Gem for propane
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is an example of how to create a propane project in atom.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/math_demo"

urls:
  bugs: https://github.com/ruby-processing/math_demo/issues
  github: https://github.com/ruby-processing/math_demo/
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
# Build settings
markdown: kramdown
